jobs:
  include:
    - stage: unit tests
      script: sudo npm test
    - stage: build
      script:
      - sudo npm run build
    - stage: deploy to staging
      if: branch=master
      script: skip
      deploy: &heroku
        provider: heroku
        app: share-doc-staging
        api_key: $HEROKU_AUTH_TOKEN
    - stage: test staging
      if: branch=master
      script: 'curl https://share-doc-staging.herokuapp.com'
    - stage: deploy to production
      if: branch=master
      script: skip
      deploy:
       <<: *heroku
       app: share-doc
    - stage: test production
      if: branch=master
      script: 'curl https://share-doc.herokuapp.com'
