language: node_js
node_js:
- stable
cache:
  npm: false

jobs:
  include:
    - stage: unit tests
      script: npm test
    - stage: build
      script: echo "Done"
          #- npm run build
    - stage: deploy
      if: branch=master
      script: skip
      deploy: &heroku
        provider: heroku
        app: share-doc
        api_key: $HEROKU_AUTH_TOKEN
    - stage: check production
      if: branch=master
      script: 'curl https://share-doc.herokuapp.com'
